### PR TITLE
Fixed scrolling, plus Mutual Data Selection

### PR DESCRIPTION
**Pull request by Fate-JH**
I synchronized the scrolling between the three TextBox controls that were simulating ByteViewer functionality.  The Scrollbar is owned by the right-most Control but it sends its messages to its neighboring Controls.  Additionally, I had to rig the three controls to handle key presses and mouse dragging and maintain line number alignment, so I also included code that allows equivalent parsed hexadecimal data and parsed character data to become highlighted at the same time.

The mouse wheel events are disabled because they would only work properly for a Control that owns a ScrollBar.  Even if I could calculate the proper caret offsets, the mouse wheel would only work on one of the three Controls.

The caret does not perfectly simulate normal Shift-selection operations in all cases but the cases where its behavior very obviously breaks from normal operations should be uncommon.

After the key press selection handler, the original event has to be consumed.  I do not like this but do not have a way of passing on the event data without causing the caret position to misalign or compromising the event data and its future handling.  This should probably be changed in the future.

### CODE REVIEW

**Comment by Fate-JH** [comment]
For some reason, I've not been getting the appropriate updates to the master repo, causing me to work on an orphaned version of this project.  Ignore this pull request.  It looks like we had very similar solutions anyway.

**Comment by Fate-JH** [comment]
Okay, I think I know what happened.  I somehow had two places where local copies were being kept.  One was up to date and the other were the files I was working on; but, that one was also based on the project's older version and that's the one I used for this pull request.  I'm just going to take my code out, put it aside, and restore everything up to the psforever/master.

**Comment by pschord** [comment]
Sorry you lost time working on these features! My current version of this was kinda a hack. I have to display three scrollbars, otherwise messages dont get passed. This is unfortunately baked deep in to the ScrollBar C# control...

Not sure how to get a better hex view without going deeper or creating a custom everything...

**Comment by pschord** [comment]
Go ahead and make a new pull request if you get some more features for this.

**Comment by Fate-JH** [comment]
I had gotten around the initial ScrollBar pain by doing the same thing you did and subclassing to get WndProc access and asking it to be shared.  To get around having to display three Scrollbars, I create key press listeners and mouse listeners and aligned the caret position for each othe the three TextBoxes.  This was at the (hopefully temporary) loss of the Mousewheel since Controls without Scrollbars seem to reject Mouswheel events.

I'll see if I can restore that.

**Pull request closed without merging**
